### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by dzwdev** [mashed-potatoes/PotatoNV-crossplatform#11]
hello
i want to use the test point method to unlock my huawei p10 boot-loader under manjaro Linux
i've installed the requirements:
python -m venv ./
source ./bin/activate
pip install -r requirements.txt
python -m usrlock

after the last line i get this error: 
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/usrlock/__main__.py", line 14, in <module>
    main.main()
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/usrlock/main.py", line 84, in main
    args = setup()
           ^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/usrlock/main.py", line 35, in setup
    args.bootloader = prompt({
                      ^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/venv/lib/python3.11/site-packages/InquirerPy/resolver.py", line 213, in prompt
    result[question_name] = question_mapping[question_type](
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/venv/lib/python3.11/site-packages/InquirerPy/prompts/list.py", line 196, in __init__
    self.content_control = InquirerPyListControl(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/venv/lib/python3.11/site-packages/InquirerPy/prompts/list.py", line 63, in __init__
    super().__init__(
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/venv/lib/python3.11/site-packages/InquirerPy/base/control.py", line 73, in __init__
    self._safety_check()
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/venv/lib/python3.11/site-packages/InquirerPy/base/control.py", line 156, in _safety_check
    raise InvalidArgument("argument choices cannot be empty")
InquirerPy.exceptions.InvalidArgument: argument choices cannot be empty
`

**Comment by dzwdev** [comment]
i found this:
python -m venv ./
source ./bin/activate
pip install -r requirements.txt
python -m usrlock

after the last line i get this error:
`python -m usrlock

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/usrlock/__main__.py", line 14, in <module>
    main.main()
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/usrlock/main.py", line 84, in main
    args = setup()
           ^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/usrlock/main.py", line 35, in setup
    args.bootloader = prompt({
                      ^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/lib/python3.11/site-packages/InquirerPy/resolver.py", line 213, in prompt
    result[question_name] = question_mapping[question_type](
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/lib/python3.11/site-packages/InquirerPy/prompts/list.py", line 196, in __init__
    self.content_control = InquirerPyListControl(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/lib/python3.11/site-packages/InquirerPy/prompts/list.py", line 63, in __init__
    super().__init__(
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/lib/python3.11/site-packages/InquirerPy/base/control.py", line 73, in __init__
    self._safety_check()
  File "/home/pc/Downloads/Huawei P10 VTR-L09/huawei unlock/PotatoNV-crossplatform-master/lib/python3.11/site-packages/InquirerPy/base/control.py", line 156, in _safety_check
    raise InvalidArgument("argument choices cannot be empty")
InquirerPy.exceptions.InvalidArgument: argument choices cannot be empty
`

**Comment by tadic-luka** [comment]
@dzwdev 
 The error happens because you are missing bootloader files. You need to fetch bootloaders submodule by running
```
# execute in top level dir of this repo
 $ git submodule update --init --recursive
```

and then just run in top level dir
```
$ python -m usrlock
```
and you will get the prompt to select bootloader

**Comment by dzwdev** [comment]
thank you very much
that is working now
i hope that you add this commands to readme:
git clone https://github.com/mashed-potatoes/PotatoNV-crossplatform.git
python -m venv ./
source ./bin/activate
pip install -r requirements.txt
git submodule update --init --recursive
python -m usrlock

then i rebooted to bootloader and enter this code:
fastboot oem unlock 1111111111111111

and now it is unlocked
thank you
